Repository Adasjo/DD2480G24-2, pull requests merged in 2024-02, with the labels that each got.

#39 issue#38
  src/utils/utils.py
  tests/test_utils.py
Labels: documentation, enhancement

#54 Issue/#53-Missing-Equal-Sign
  requirements.txt
Labels: bug

#55 Issue/#12 CI#4 History CI Build History
  .gitignore
  README.md
  logs/.gitkeep
  src/app.py
  src/logs/log_individual.py
  src/logs/logs_all.py
  tests/test_log_individual.py
  tests/test_logs_all.py
Labels: documentation, enhancement

#75 Issue/#73 Readme Missing Documentation
  README.md
Labels: documentation

#77 Issue/#76 Fix Github Details Target URL
  src/build/run_build.py
Labels: bug

#82 doc: relocated 2nd Documentation
  README.md
Labels: documentation

#85 Issue/#84 Fixing Logging Module
  .gitignore
  src/build/run_build.py
Labels: bug

#88 Issue/#87 remove unused symbols and code
  src/build/run_build.py
  tests/test_run_build.py
Labels: bug

#90 Issue/#89-makefile-test-wrong-directory
  Makefile
Labels: bug

#92 Issue/#91 documentation add missing modules
  docs/source/build.rst
  docs/source/conf.py
  docs/source/dummy.rst
  docs/source/index.rst
  docs/source/log_individual.rst
  docs/source/logs_all.rst
  docs/source/modules.rst
  docs/source/run_build.rst
  docs/source/run_syntax.rst
  docs/source/run_tests.rst
  docs/source/src.rst
  docs/source/syntax.rst
  docs/source/tests.rst
Labels: documentation
